Создание сервера и обработка запросов
alesyatyzhikova/mesto-backend pull request #1
Opened 2020-03-01 10:43 UTC by alesyatyzhikova

Сделано в ветке:
Добавила линтер и editorconfig
Создала express-сервер - app.js
Раздача статичных файлов в папке public
Создала   API для запросов карточек и пользователей и не найденные ресуросв - users, cards, notFound

2020-03-02 04:39 UTC, mrprovoker requested changes
Добрый день!

Очень хорошая работа! Отличное README, хорошая структура и архитектура проекта, нет ошибок линтера.

Есть несколько критичных замечаний.

**Надо исправить:**
1. По заданию в папке public должен находиться только собранный фронтенд приложения, а не исходники.
2. Запрос за пользователем сейчас возвращает массив, например `http://localhost:3000/users/dbfe53c3c4d568240378b0c6`. А должен возвращаться только объект с пользователем. Сейчас очень сложно написан код поиска пользователя. Можно проще, используя метод `find` у массивов.
Массив в API-обработчиках возвращается, когда запрос подразумевает вернуть список объектов (например список ВСЕХ пользователей). На запрос, где мы явно передаем id пользователя, ожидается возвращением именно самого объекта пользователя.
3. GET-запрос на несуществующий путь возвращает статус 200. Ожидается статус 404

Можно лучше:
- Обычно файл `README.md` принято называть заглавными буквами.
- В package.json cекция main говорит о том, что главный файл `index.js`. Такого файла в корне проекта нет.
- В package.json пустая секция "description" и "author". Рекомендуется заполнить данные секции.
- Хорошим стилем является в JS-файлах отделять пустой строкой подключение бибилиотек из `node_modules` и файлов из проекта. Например в файле `routes/users.js`
- В app.js вместо `app.use('/', notFound);` можно писать просто `app.use(notFound);`. Так как это последняя мидлвара в проекте и если до нее дошел запрос - значит мы точно попали не по тому урлу.
- В routes/api/notFound.js вместо `router.all('/*'` можно писать проще - `router.all('*'`.


При правках данный pull request закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же pull request'е.


Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-03-02 09:27 UTC, alesyatyzhikova commented
Исправила замечания по CR:
- В папке public находится только собранный фронтенд;
- Запрос за пользователем возвращает объект;
- Переписан код поиска пользователя через метод find;
- GET-запрос на несуществующий путь возвращает статус 404;

По замечаниям можно лучше исправлено, файл README.md почему-то в локальном переименован, при  пуше загрузился со старым названием

2020-03-02 16:52 UTC, mrprovoker approved these changes
Спасибо за правки, теперь все хорошо!

Все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!

2020-03-02 16:52 UTC, mrprovoker commented on app.js
> +const notFound = require('./routes/notFound');
Можно лучше:
- Возможно я ввел в заблуждение. Под рекомендуемым стилем я имел ввиду следующее:
```
const express = require('express');
const path = require('path');

const cards = require('./routes/api/cards');
const users = require('./routes/api/users');
const notFound = require('./routes/api/notFound');
```

То есть сначала идут модули из `node_modules`. А потом через пустую строку идет подключение файлов проекта.

2020-03-02 16:52 UTC, mrprovoker commented on routes/users.js
>      res.status(404).json({ message: 'Нет пользователя с таким id' });
Можно лучше:
- Необходим return внутри if.
Сейчас, если пользователь не найден сначала отправится ответ `res.status(404).json({ message: 'Нет пользователя с таким id' });`, а потом еще `res.json(foundUser);`
За одно выполнение обработчика должен вызываться только один `res.json`, иначе это в будущем может привести к ошибкой.
Рекомендую перед `merge` данного пулл реквеста исправить данный момент.

2020-03-03 08:08 UTC, merged

2020-03-03 08:10 UTC, alesyatyzhikova commented on routes/users.js
>      res.status(404).json({ message: 'Нет пользователя с таким id' });
Ошибки исправила, смержила.
Если работа принята, подтвердите это в интерфейсе Практикума, пожалуйста)