Работа с базой данных
alesyatyzhikova/mesto-backend pull request #2
Opened 2020-03-09 19:11 UTC by alesyatyzhikova

В данном коммите было реализовано:
- Подключилась к MongoDB
- Создала схемы и модели для сущностей пользователя и карточек
- Создала контроллеры и роуты для пользователей и карточек
- Реализовала временное решение для авторизации
- Удалила статику для фронта

2020-03-10 11:20 UTC, aarefiev requested changes
Очень хорошая работа. Вижу есть полностью реализованное дополнительное задание :+1: .

Хорошее описание проекта :+1:. Проект хорошо структурирован, элементы сгруппированы в группы по принадлежности (роуты, контроллеры, модели). Для статической проверки синтаксиса подключен линтер `eslint`, устанавливающий соответствие стайлгайду _Airbnb_. Запуск линтера завершается без ошибок. Запустить сервер и проверить работу не удалось. Запуск сервера сопровождается ошибкой и завершением работы.

**Нужно исправить:**
1. Сервер не запускается.

2020-03-10 11:20 UTC, aarefiev commented on models/card.js
> +    },
Нужно исправить: сервер не запускается.
Ошибка:
```bash
$ npm run dev

> sprint_12@2.0.0 dev /home/jmi/work/ya-reviews/mesto-backend
> nodemon app

[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
/home/jmi/work/ya-reviews/mesto-backend/node_modules/mongoose/lib/schematype.js:756
      throw new Error(msg);
      ^

Error: Invalid validator. Received (undefined) undefined. See http://mongoosejs.com/docs/api.html#schematype_SchemaType-validate
    at SchemaString.SchemaType.validate (/home/jmi/work/ya-reviews/mesto-backend/node_modules/mongoose/lib/schematype.js:756:13)
    at SchemaString.SchemaType.validate (/home/jmi/work/ya-reviews/mesto-backend/node_modules/mongoose/lib/schematype.js:758:10)
    at SchemaString.SchemaType (/home/jmi/work/ya-reviews/mesto-backend/node_modules/mongoose/lib/schematype.js:103:18)
    at new SchemaString (/home/jmi/work/ya-reviews/mesto-backend/node_modules/mongoose/lib/schema/string.js:30:14)
    at Schema.interpretAsType (/home/jmi/work/ya-reviews/mesto-backend/node_modules/mongoose/lib/schema.js:986:10)
    at Schema.path (/home/jmi/work/ya-reviews/mesto-backend/node_modules/mongoose/lib/schema.js:678:27)
    at Schema.add (/home/jmi/work/ya-reviews/mesto-backend/node_modules/mongoose/lib/schema.js:517:14)
    at new Schema (/home/jmi/work/ya-reviews/mesto-backend/node_modules/mongoose/lib/schema.js:130:10)
    at Object.<anonymous> (/home/jmi/work/ya-reviews/mesto-backend/models/card.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[nodemon] app crashed - waiting for file changes before starting...
```

2020-03-10 11:31 UTC, alesyatyzhikova commented on models/card.js
> +    },
переборщила с валидатором. Исправила

2020-03-11 11:22 UTC, aarefiev requested changes
Отлично сервер начал запускаться. Сейчас удалось проверить все роуты. Нашёл несколько ошибок и улучшений.

**Нужно исправить:**
1. При сохранении пользователя происходит ошибка валидации.
2. При сохранении карточки происходит ошибка валидации.
3. Можно установить лайки при создании карточки.
4. При установке лайка на несуществующую карточку возвращается 200.
5. При удалении лайка с несуществующей карточки возвращается 200.

**Можно лучше:**
1. Вынести настройки в отдельный конфигурационный файл.
2. Использовать встроенные хелперы `mongoose` для обработки несуществующей записи.

2020-03-11 11:22 UTC, aarefiev commented on models/user.js
> +        return validator.isUrl(value);
Нужно исправить: при сохранении пользователя происходит ошибка валидации.
```json
{
    "message": "Что-то пошло не так",
    "err": "user validation failed: avatar: validator.isUrl is not a function"
}
```
```suggestion
        return validator.isURL(value);
```

2020-03-11 11:22 UTC, aarefiev commented on models/card.js
> +        return validator.isUrl(value);
Нужно исправить: при сохранении карточки происходит ошибка валидации.
```json
{
    "message": "Что-то пошло не так",
    "err": "card validation failed: link: validator.isUrl is not a function"
}
```
```suggestion
        return validator.isURL(value);
```

2020-03-11 11:22 UTC, aarefiev commented on controllers/cards.js
> +  Card.create({ name, link, owner: ownerId, likes })
Нужно исправить: можно установить лайки при создании карточки.
По заданию для установки и снятия лайка с карточки нужно реализовать два отдельных роута.

2020-03-11 11:22 UTC, aarefiev commented on controllers/cards.js
> +    })
Нужно исправить: при установке лайка на несуществующую карточку возвращается 200.
Это происходит потому, что не обрабатывается ситуация, когда запись в базе с указанным `id` не существует. В случае отстуствия записи в базе нужно возвращать [404 Not Found](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/404).

2020-03-11 11:22 UTC, aarefiev commented on controllers/cards.js
> +    })
Нужно исправить: при удалении лайка с несуществующей карточки возвращается 200.
Аналогично комментарию для `likeCard()`.

2020-03-11 11:22 UTC, aarefiev commented on controllers/cards.js
> +      }
Можно лучше: использовать встроенные хелперы `mongoose` для обработки несуществующей записи.
В `mongoose` по-умолчанию методы, которые делают выборку значений из базы данных по какому-то условию, возвращают `null` в случае отсутствия записи в базе данных. Для того, чтобы отловить эту ситуацию есть хелпер [`.orFail()`](https://mongoosejs.com/docs/api.html#query_Query-orFail).

Хелпер принимает функцию, которая выполняет _reject_ промиса. Если функция будет возвращать какое-то значение, оно будет передано в `.catch()` блок, если нет, то будет отправлено значение по-умолчанию.

Но это не всё. Ещё нужно корректно прокинуть код ошибки. Так как внутри `orFail()` хелпера можно передать любое значение, то я рекомендую создать отдельный модуль для ошибки. Модуль будет содержать класс, который наследует класс `Error` добавляя туда свойство, в котором будет определен HTTP код ошибки. Например для 404 он будет выглядеть так:
```js
// errors/notFoundError.js
class NotFoundError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 404;
  }
}

module.exports = NotFoundError;
```

Далее отправка ошибки в `orFail()` сводится к следующему:
```js
.orFail(() => new NotFoundError('Карточка не найдена'))
```

А передача кода уходит в `.catch()` блок:
```js
.catch((err) => res.status(err.statusCode || 500).send({ message: 'Что-то пошло не так', err: err.message }));
```

2020-03-11 11:22 UTC, aarefiev commented on app.js
> +mongoose.connect('mongodb://localhost:27017/mestodb', {
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Если оставить определение значений в коде, то возникает несколько очевидных проблем:
- изменение какой-то настройки требует изменений всех файлов, где она используется,
- нельзя использовать отдельные настройки для разработки и продакшена

Лучше создать отдельный файл (например, `config.js`) и в нём уже заполнять те настройки, которые будут использоваться в проекте (например, секретный ключ, порт сервера или адрес для подключения к базе данных). Далее этот файл подключать в тех файлах, где необходимо получить значения. Пример файла:
```js
module.exports.PORT = process.env.PORT || 3000;
module.exports.DATABASE_URL = 'mongodb://localhost:27017/mestodb';
```

2020-03-14 08:27 UTC, alesyatyzhikova commented on app.js
> +mongoose.connect('mongodb://localhost:27017/mestodb', {
Исправила:
- Валидацию в моделях;
- Отработку ошибок в контроллерах;
- Добавила файл конфигурации для настроек;
- Удалила возможность создать карточку с лайком и исправила возврат статуса при несуществующей карточке

2020-03-15 04:56 UTC, aarefiev approved these changes
Отлично. Ошибки исправлены. Новых не обнаружено.
Работа принимается 🎉 .

2020-03-15 05:57 UTC, merged